### ISSUE TITLE
"TypeError: Type str doesn't support the buffer API" when receiving CString appmessage from Pebble

### ISSUE THREAD

**Issue by OwenSSH** [pebble/libpebble2#13]
After sending a CString using dict_write_cstring the following error occurs

```
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.2/dist-packages/libpebble2/communication/__init__   .py", line 88, in run_sync
    self.pump_reader()
  File "/usr/local/lib/python3.2/dist-packages/libpebble2/communication/__init__   .py", line 75, in pump_reader
    self._handle_watch_message(message)
  File "/usr/local/lib/python3.2/dist-packages/libpebble2/communication/__init__   .py", line 139, in _handle_watch_message
    self.event_handler.broadcast_event((_EventType.Watch, type(packet)), packet)
  File "/usr/local/lib/python3.2/dist-packages/libpebble2/events/threaded.py", l   ine 44, in broadcast_event
    handler(*args)
  File "/usr/local/lib/python3.2/dist-packages/libpebble2/services/appmessage.py   ", line 58, in _handle_message
    result[t.key] = t.data.split('\x00')[0]
TypeError: Type str doesn't support the buffer API
```

changing

```
elif t.type == AppMessageTuple.Type.CString:
    result[t.key] = t.data.split('\x00')[0]
```

to 

```
elif t.type == AppMessageTuple.Type.CString:
    result[t.key] = t.data.decode("utf-8")
```

seems to fix this issue

**Comment by Katharine** [comment]
Sorry! I added a test around this so it shouldn't happen again.

Ended up with this:

``` python
result[t.key] = t.data.split(b'\x00')[0].decode('utf-8', errors='replace')
```
